import turtle
turtle.Screen().bgcolor("black")
scr = turtle.Screen()
scr.setup(800, 800)
turtle.title("Welcome to the turtle in python. You will be seeing various shapes like triange and a rectangle")
t = turtle.Turtle()
t.pencolor("red")
t.forward(50)
t.right(60)
t.backward(50)
t.right(60)
t.forward(50)
t.right(60)
turtle.Screen().bgcolor("red")
t.pencolor("purple")
t.forward(80)
t.left(90)
t.forward(30)
t.left(90)
t.forward(80)
t.left(90)
t.forward(30)
turtle.Screen().bgcolor("white")
