import turtle
turtle.Screen().bgcolor("red")
scr = turtle.Screen()
scr.setup(400, 300)
turtle.title("Welcome to the turtle in python. You will be seeing a Star")
board = turtle.Turtle()
turtle.pencolor("purple")
board.forward(100)
board.left(120)
board.forward(100)
board.left(120)
board.forward(100)

board.penup()
board.right(150)
board.forward(50)

board.pendown()
board.right(90)
board.forward(100)
board.right(120)
board.forward(100)
board.right(120)
board.forward(100)
turtle.done()