file1 = input("What is the file you want to import to?")
file2 = input("What is the file you want to import to for the first file?")
f1 = open(file1, 'r')
f2 = open(file2, 'r')
print("This is your file of students and their fav subjects before you handled them with the 2nd file", f1.read())
print("This is your file of students and their fav subjects of the 2nd file", f2.read())
f1.close()
f2.close()
f1 = open(file1, 'a+')
f2 = open(file2, 'r')
f1.write(f2.read())
f1.seek(0)
f2.seek(0)
print("Now your students are", f1.read())
print("Your 2nd file is", f2.read())
f1.close()
f2.close()
